group 'sk.fourq.otaupdate'
version '1.0-SNAPSHOT'

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace "sk.fourq.otaupdate"

    compileSdk 35

    defaultConfig {
        minSdk 21
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        disable += 'InvalidPackage'
    }
}

dependencies {
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    // https://mvnrepository.com/artifact/commons-codec/commons-codec
    implementation 'commons-codec:commons-codec:1.18.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
